apiVersion: v1
kind: Namespace
metadata:
    name: mariadb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-data-pv
  namespace: mariadb
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mariadb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data-pvc
  namespace: mariadb
spec:
  storageClassName: local-path
  volumeName: mariadb-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb
  namespace: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: docker-registry1.mariadb.com/library/mariadb:latest
          imagePullPolicy: Always
          env:
          - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
            value: "true"
          ports:
            - containerPort: 3306
              name: mariadb
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mariadb-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: mariadb
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: mariadb
  selector:
    app: mariadb
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.0.79
