apiVersion: v1
kind: Namespace
metadata:
    name: influxdb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-data-pv
  namespace: influxdb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: nfs-server.default.svc.cluster.local/share##
    volumeAttributes:
      server: 192.168.0.3
      share: /volume1/kubernetes/influxdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data-pvc
  namespace: influxdb
spec:
  storageClassName: nfs-csi
  volumeName: influxdb-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - image: influxdb:1.11.8
          name: influxdb
          ports:
            - containerPort: 8086
              name: influxdb
            - containerPort: 8088
              name: rpc
          volumeMounts:
            - mountPath: /etc/influxdb/influxdb.conf
              name: influxdb-config
              subPath: influxdb.conf
              readOnly: true
            - mountPath: /var/lib/influxdb
              name: data
      volumes:
        - name: influxdb-config
          configMap:
            name: influxdb-config
        - name: data
          persistentVolumeClaim:
            claimName: influxdb-data-pvc
---
apiVersion: v1

kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: influxdb
data:
  influxdb.conf: |+
    reporting-disabled = true
    bind-address = ":8088"

    [meta]
      dir = "/var/lib/influxdb/meta"

    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
      series-id-set-cache-size = 100
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: influxdb
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - name: influxdb
    port: 8086
    protocol: TCP
    targetPort: 8086
  - name: rpc
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: influxdb
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.0.75
