{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myApp.fullname" . }}
  labels:
    {{- include "myApp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "myApp.selectorLabels" . | nindent 4 }}
{{- end }}