apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-ui-data-pv
  namespace: docker-registry-ui
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/k3s/volumes/docker-registry-ui/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-ui-data-pvc
  namespace: docker-registry-ui
spec:
  storageClassName: local-path
  volumeName: docker-registry-ui-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-registry-ui
  name: docker-registry-ui
  namespace: docker-registry-ui
spec:
  selector:
    matchLabels:
      app: docker-registry-ui
  template:
    metadata:
      labels:
        app: docker-registry-ui
    spec:
      containers:
        - name: docker-registry-ui
          image: joxit/docker-registry-ui:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: SINGLE_REGISTRY
            value: "true"
          - name: REGISTRY_TITLE
            value: "Docker Registry UI"
          - name: DELETE_IMAGES
            value: "true"
          - name: SHOW_CONTENT_DIGEST
            value: "true"
          - name: NGINX_PROXY_PASS_URL
            value: "https://192.168.0.74:5000"
          - name: SHOW_CATALOG_NB_TAGS
            value: "true"
          - name: CATALOG_MIN_BRANCHES
            value: "1"
          - name: CATALOG_MAX_BRANCHES
            value: "1"
          - name: TAGLIST_PAGE_SIZE
            value: "100"
          - name: REGISTRY_SECURED
            value: "false"
          - name: CATALOG_ELEMENTS_LIMIT
            value: "1000"
          ports:
            - containerPort: 80
              name: registry
          volumeMounts:
            - mountPath: /var/lib/registry
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: docker-registry-ui-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
  namespace: docker-registry-ui
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - name: docker-registry-ui
    port: 80
    targetPort: registry
  selector:
    app: docker-registry-ui
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.0.77
