apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/joakimberglund/home-setup.git"
    targetRevision: main
    path: "kubernetes/components/docker-registry-ui"
  destination:
    server: https://kubernetes.default.svc
    namespace: docker-registry-ui
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
