apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/joakimberglund/home-setup.git'
    targetRevision: main
    path: "kubernetes/grafana"
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
