apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://downloads.portainer.io/ce-lts/portainer-lb.yaml'
    chart: portainer
    targetRevision: 2.33.1
  - repoURL: "https://github.com/joakimberglund/home-setup.git"
    targetRevision: HEAD
    path: "kubernetes/components/portainer"
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
